# Generated by Django 5.2.6 on 2025-09-25 17:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Commandes', '0004_initial'),
        ('Menus', '0003_menu_description_menu_titre_menuplat_prix_and_more'),
        ('Plats', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commande',
            unique_together={('utilisateur', 'menu', 'plat')},
        ),
    ]
