# Generated by Django 5.2.6 on 2025-09-25 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Avis', '0002_initial'),
        ('Plats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='plat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Plats.plat'),
        ),
    ]
