# Generated by Django 5.2.6 on 2025-09-25 14:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi')], max_length=10)),
                ('date', models.DateField()),
                ('site', models.CharField(choices=[('Danga', 'Danga'), ('Campus', 'Campus')], max_length=100)),
                ('est_publie', models.BooleanField(default=False)),
                ('date_limite_commande', models.DateTimeField()),
                ('max_commandes', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_updated', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['date', 'site'],
            },
        ),
        migrations.CreateModel(
            name='MenuPlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_prevue', models.IntegerField(default=0)),
                ('quantite_commandee', models.IntegerField(default=0)),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Menus.menu')),
            ],
        ),
    ]
